### ISSUE TITLE
Improvement idea: displaying HTTP Body too

### ISSUE THREAD

**Issue by richard-pal** [Nitrama/HTTP-Header-Live#25]
As an improvement, it would be very good if this plugin would show not just the headers but also the body of the HTTP messages. 

I am training students on creating web-applications, and there is no such plugin available which would display the complete raw HTTP messages in a clear and easy-to-overview way. (Dev.Toolbar supports it, but with a lot of clicking here and there, which confuses the students)
If you could improve the plugin in this direction, that would be awesome!

**Comment by Nitrama** [comment]
Since the addon is inspired by "Live HTTP Headers" it wouldn't fit in very well.

But in itself it's not a bad idea.
I would have to think a little bit about how best to integrate it.

If you have a good idea please tell me. 
Maybe with a picture or something.


And thank you that it is really used productively. That makes me very happy.
